<?php
/**
 * InfiniteScroll - Magento Integration
 * @version    2.0
 * 
 * @author     Gabriel Somoza (me@gabrielsomoza.com)
 * @link       http://gabrielsomoza.com/
 * @category   Strategery
 * @package    Strategery_Infinitescroll	   
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
$helper = $this->helper('infinitescroll');  ?>
jQuery(document).ready(function ($) {
    $('<?php echo $helper->getConfigData('selectors/content') ?>').infinitescroll({
        <?php echo $helper->getJsConfig(); ?>
    });
});