<?php
/** @var $this Strategery_Infinitescroll2_Block_Init */
/**
 * InfiniteScroll - Magento Integration
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0),
 * available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * @category   Strategery
 * @package    Strategery_Infinitescroll2
 * @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @copyright  Copyright (c) 2011 Strategery Inc. (http://usestrategery.com)
 *
 * @author     Enrique Piatti (contacto@enriquepiatti.com)
 */
?>
<?php if($this->isEnabled()): ?>
<?php
	$configData = $this->getConfigData();
	$jsConfig = $this->getJsConfig();
?>
<script>
	var StrategeryInfiniteScroll = {
		// TODO: js fallback (use yepnope?)
		loadScript : function(url, callback) {
			var safelistener = function(){
				try {
					callback();
				} catch(e) {
					console.log(e.message);
				}
			};
			var scriptElt = document.createElement("script");
			scriptElt.type = "text/javascript";
			// Opera has readyState too, but does not behave in a consistent way
			if (scriptElt.readyState && scriptElt.onload !== null) {
				// IE only (onload===undefined) not Opera (onload===null)
				scriptElt.onreadystatechange = function() {
					if ( scriptElt.readyState === "loaded" || scriptElt.readyState === "complete" ) {
						// Avoid memory leaks (and duplicate call to callback) in IE
						scriptElt.onreadystatechange = null;
						safelistener();
					}
				};
			} else {
				// other browsers (DOM Level 0)
				scriptElt.onload = safelistener;
			}
			scriptElt.src = url;
			document.getElementsByTagName("head")[0].appendChild(scriptElt);
		},
		init: function(){
			jQuery.noConflict();
			StrategeryInfiniteScroll.loadScript("<?php echo $this->getJsUrl('jquery/infinitescroll2/jquery.infinitescroll.js') ?>", function(){
				StrategeryInfiniteScroll.loadScript("<?php echo $this->getJsUrl('jquery/infinitescroll2/behaviors/infinitescroll-magento.js') ?>", function(){
					jQuery(function($) {
						$('<?php echo $configData ?>').infinitescroll({
								<?php echo $jsConfig; ?>
							},
							<?php echo Mage::getStoreConfig('infinitescroll2/callbacks/processed_callback')?>
						);
						<?php if(Mage::getStoreConfig('infinitescroll2/design/hide_toolbar')): ?>
						$('<?php echo Mage::getStoreConfig('infinitescroll2/selectors/toolbar') ?>').hide();
						<?php endif ?>
						<?php if(Mage::getStoreConfig('infinitescroll2/design/hide_pagination')): ?>
						$('<?php echo Mage::getStoreConfig('infinitescroll2/selectors/pagination') ?>').hide();
						<?php endif ?>
					});
				});
			});

		}
	};
	if (typeof jQuery == 'undefined') {
		// try loading jQuery from the CDN first
		StrategeryInfiniteScroll.loadScript("//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js", function(){
			// use local jQuery fallback
			if (typeof jQuery == 'undefined') {
				StrategeryInfiniteScroll.loadScript("<?php echo $this->getJsUrl('jquery/jquery.latest.min.js') ?>", function(){
					StrategeryInfiniteScroll.init();
				});
			}else {
				StrategeryInfiniteScroll.init();
			}
		});
	} else {
		StrategeryInfiniteScroll.init();
	}
</script>
<?php endif ?>
