<?php
/**
 * InfiniteScroll - Magento Integration
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0),
 * available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * @category   Strategery
 * @package    Strategery_Infinitescroll2	   
 * @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @copyright  Copyright (c) 2011 Strategery Inc. (http://usestrategery.com)
 * 
 * @author     Gabriel Somoza (me@gabrielsomoza.com)
 * @link       http://gabrielsomoza.com/
 */
$helper = $this->helper('infinitescroll2');
?>
jQuery(document).ready(function ($) {
    $('<?php echo $helper->getConfigData('selectors/content') ?>').infinitescroll({
        <?php echo $helper->getJsConfig(); ?>
    },
    <?php echo Mage::getStoreConfig('infinitescroll2/callbacks/processed_callback')?>
    );
});